# Generated by Django 2.1.3 on 2018-11-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroom',
            name='room_id',
            field=models.CharField(max_length=255, verbose_name='RoomID for associated user'),
        ),
    ]
