# Generated by Django 2.1.3 on 2018-11-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0002_auto_20181127_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroom',
            name='room_id',
        ),
        migrations.AddField(
            model_name='userroom',
            name='room_name',
            field=models.CharField(default='', max_length=255, verbose_name='Room name for associated user'),
        ),
    ]
