# Generated by Django 2.1.3 on 2018-12-11 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websocket', '0003_auto_20181127_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_room_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBoardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(help_text='player id will be 0 or 1 or 2 or 3', max_length=1)),
                ('is_online', models.CharField(help_text='1=online, 0=offline', max_length=1)),
                ('token_data', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='livechatroom',
            name='playerlist_details',
            field=models.ManyToManyField(to='websocket.PlayerBoardDetail'),
        ),
    ]
