# Generated by Django 2.1.3 on 2018-12-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0004_auto_20181211_1417'),
    ]
    atomic = False
    operations = [
        migrations.RenameModel(
            old_name='LiveChatRoom',
            new_name='LiveGameRoom',
        ),
    ]
